-- Task 14: install one approved core rule for every Task 11 threat category.
-- Rules are seeded disabled so deployment does not silently activate new detection policy.
-- Category availability is temporarily changed only inside this migration transaction and restored before commit.
LOCK TABLE threat_categories IN SHARE ROW EXCLUSIVE MODE;
CREATE TEMP TABLE task14_threat_category_state ON COMMIT DROP AS
  SELECT code, enabled, updated_at FROM threat_categories WHERE code IN ('BRUTE_FORCE', 'CREDENTIAL_ATTACK', 'PRIVILEGE_ESCALATION', 'SUSPICIOUS_ACCOUNT_ACTIVITY', 'UNAUTHORIZED_ACCESS', 'RECONNAISSANCE', 'SUSPICIOUS_NETWORK_ACTIVITY', 'PHISHING_SOCIAL_ENGINEERING', 'MALWARE', 'RANSOMWARE', 'DENIAL_OF_SERVICE', 'DATA_EXFILTRATION', 'WEB_APPLICATION_ATTACK', 'INSIDER_THREAT', 'SUPPLY_CHAIN_COMPROMISE');

UPDATE threat_categories SET enabled = true WHERE code IN ('BRUTE_FORCE', 'CREDENTIAL_ATTACK', 'PRIVILEGE_ESCALATION', 'SUSPICIOUS_ACCOUNT_ACTIVITY', 'UNAUTHORIZED_ACCESS', 'RECONNAISSANCE', 'SUSPICIOUS_NETWORK_ACTIVITY', 'PHISHING_SOCIAL_ENGINEERING', 'MALWARE', 'RANSOMWARE', 'DENIAL_OF_SERVICE', 'DATA_EXFILTRATION', 'WEB_APPLICATION_ATTACK', 'INSIDER_THREAT', 'SUPPLY_CHAIN_COMPROMISE');

INSERT INTO detection_rules(name, description, enabled, definition, threat_level, category_code) VALUES
  ('SX-CORE-001 Brute force authentication failures', 'Detects five failed login events from the same source IP against the same user within five minutes.', false, '{"schemaVersion":1,"conditions":[{"field":"type","operator":"equals","value":"authentication"},{"field":"action","operator":"equals","value":"login"},{"field":"status","operator":"equals","value":"failed"}],"threshold":5,"windowSeconds":300,"groupBy":["sourceIp","user"]}'::jsonb, 'HIGH'::threat_level, 'BRUTE_FORCE'),
  ('SX-CORE-002 Credential attack indicators', 'Detects repeated failed authentication events explicitly labeled as password spraying or credential stuffing from one source IP.', false, '{"schemaVersion":1,"conditions":[{"field":"type","operator":"equals","value":"authentication"},{"field":"action","operator":"in","value":["password_spray","credential_stuffing"]},{"field":"status","operator":"equals","value":"failed"}],"threshold":3,"windowSeconds":300,"groupBy":["sourceIp"]}'::jsonb, 'HIGH'::threat_level, 'CREDENTIAL_ATTACK'),
  ('SX-CORE-003 Privilege escalation action', 'Detects an authorization event explicitly reporting a successful privilege escalation, role elevation, or administrator grant.', false, '{"schemaVersion":1,"conditions":[{"field":"type","operator":"equals","value":"authorization"},{"field":"action","operator":"in","value":["privilege_escalation","role_elevation","admin_grant"]},{"field":"status","operator":"in","value":["success","allowed"]}],"threshold":1,"windowSeconds":60,"groupBy":["user","host"]}'::jsonb, 'CRITICAL'::threat_level, 'PRIVILEGE_ESCALATION'),
  ('SX-CORE-004 Suspicious account activity flag', 'Detects account events explicitly marked suspicious by the normalized source evidence.', false, '{"schemaVersion":1,"conditions":[{"field":"type","operator":"equals","value":"account"},{"field":"status","operator":"equals","value":"suspicious"}],"threshold":1,"windowSeconds":300,"groupBy":["user"]}'::jsonb, 'HIGH'::threat_level, 'SUSPICIOUS_ACCOUNT_ACTIVITY'),
  ('SX-CORE-005 Repeated unauthorized access attempts', 'Detects three denied access events from the same source IP against the same user within five minutes.', false, '{"schemaVersion":1,"conditions":[{"field":"type","operator":"equals","value":"access"},{"field":"status","operator":"equals","value":"denied"}],"threshold":3,"windowSeconds":300,"groupBy":["sourceIp","user"]}'::jsonb, 'HIGH'::threat_level, 'UNAUTHORIZED_ACCESS'),
  ('SX-CORE-006 Reconnaissance activity', 'Detects repeated events explicitly classified as reconnaissance scans, probes, or discovery activity from one source toward one destination.', false, '{"schemaVersion":1,"conditions":[{"field":"type","operator":"equals","value":"reconnaissance"},{"field":"action","operator":"in","value":["scan","probe","discovery"]}],"threshold":3,"windowSeconds":120,"groupBy":["sourceIp","destinationIp"]}'::jsonb, 'MEDIUM'::threat_level, 'RECONNAISSANCE'),
  ('SX-CORE-007 Suspicious network activity flag', 'Detects network events explicitly marked suspicious by normalized source evidence.', false, '{"schemaVersion":1,"conditions":[{"field":"type","operator":"equals","value":"network"},{"field":"status","operator":"equals","value":"suspicious"}],"threshold":1,"windowSeconds":60,"groupBy":["sourceIp","destinationIp"]}'::jsonb, 'HIGH'::threat_level, 'SUSPICIOUS_NETWORK_ACTIVITY'),
  ('SX-CORE-008 Phishing or social engineering report', 'Detects events explicitly classified as phishing and marked detected or reported by source evidence.', false, '{"schemaVersion":1,"conditions":[{"field":"type","operator":"equals","value":"phishing"},{"field":"status","operator":"in","value":["detected","reported"]}],"threshold":1,"windowSeconds":300,"groupBy":["user"]}'::jsonb, 'HIGH'::threat_level, 'PHISHING_SOCIAL_ENGINEERING'),
  ('SX-CORE-009 Malware event', 'Detects events explicitly classified as malware and marked detected, blocked, or executed by source evidence.', false, '{"schemaVersion":1,"conditions":[{"field":"type","operator":"equals","value":"malware"},{"field":"status","operator":"in","value":["detected","blocked","executed"]}],"threshold":1,"windowSeconds":60,"groupBy":["host"]}'::jsonb, 'HIGH'::threat_level, 'MALWARE'),
  ('SX-CORE-010 Ransomware event', 'Detects events explicitly classified as ransomware and marked detected, blocked, or executed by source evidence.', false, '{"schemaVersion":1,"conditions":[{"field":"type","operator":"equals","value":"ransomware"},{"field":"status","operator":"in","value":["detected","blocked","executed"]}],"threshold":1,"windowSeconds":60,"groupBy":["host"]}'::jsonb, 'CRITICAL'::threat_level, 'RANSOMWARE'),
  ('SX-CORE-011 Denial of service indicators', 'Detects repeated network events explicitly labeled DoS or DDoS against the same destination or host within one minute.', false, '{"schemaVersion":1,"conditions":[{"field":"type","operator":"equals","value":"network"},{"field":"action","operator":"in","value":["dos","ddos"]},{"field":"status","operator":"in","value":["detected","active","blocked"]}],"threshold":3,"windowSeconds":60,"groupBy":["destinationIp","host"]}'::jsonb, 'CRITICAL'::threat_level, 'DENIAL_OF_SERVICE'),
  ('SX-CORE-012 Data exfiltration event', 'Detects data-transfer events explicitly labeled as exfiltration and marked detected, blocked, or successful by source evidence.', false, '{"schemaVersion":1,"conditions":[{"field":"type","operator":"equals","value":"data_transfer"},{"field":"action","operator":"equals","value":"exfiltration"},{"field":"status","operator":"in","value":["detected","blocked","success"]}],"threshold":1,"windowSeconds":300,"groupBy":["user","host"]}'::jsonb, 'CRITICAL'::threat_level, 'DATA_EXFILTRATION'),
  ('SX-CORE-013 Web application attack event', 'Detects web-application events explicitly labeled as SQL injection, XSS, path traversal, or command injection.', false, '{"schemaVersion":1,"conditions":[{"field":"type","operator":"equals","value":"web_application"},{"field":"action","operator":"in","value":["sql_injection","xss","path_traversal","command_injection"]},{"field":"status","operator":"in","value":["detected","blocked","attempted"]}],"threshold":1,"windowSeconds":60,"groupBy":["sourceIp","destinationIp"]}'::jsonb, 'HIGH'::threat_level, 'WEB_APPLICATION_ATTACK'),
  ('SX-CORE-014 Insider threat classification', 'Detects events explicitly classified by source evidence as suspected or detected insider-threat activity; it does not infer insider intent.', false, '{"schemaVersion":1,"conditions":[{"field":"type","operator":"equals","value":"insider_threat"},{"field":"status","operator":"in","value":["suspected","detected"]}],"threshold":1,"windowSeconds":300,"groupBy":["user","host"]}'::jsonb, 'HIGH'::threat_level, 'INSIDER_THREAT'),
  ('SX-CORE-015 Supply chain compromise classification', 'Detects events explicitly classified by source evidence as detected or confirmed supply-chain compromise activity.', false, '{"schemaVersion":1,"conditions":[{"field":"type","operator":"equals","value":"supply_chain_compromise"},{"field":"status","operator":"in","value":["detected","confirmed"]}],"threshold":1,"windowSeconds":300,"groupBy":["host"]}'::jsonb, 'CRITICAL'::threat_level, 'SUPPLY_CHAIN_COMPROMISE');

INSERT INTO rule_mitre_mappings(rule_id, mapping_id)
SELECT r.id, m.id
FROM detection_rules r
JOIN mitre_mappings m ON m.technique_id = 'T1110'
WHERE r.name IN ('SX-CORE-001 Brute force authentication failures', 'SX-CORE-002 Credential attack indicators');

UPDATE threat_categories category
SET enabled = state.enabled, updated_at = state.updated_at
FROM task14_threat_category_state state
WHERE category.code = state.code;
