const INITIAL_RULES = Object.freeze([
  {
    name: 'SX-CORE-001 Brute force authentication failures',
    description: 'Detects five failed login events from the same source IP against the same user within five minutes.',
    enabled: false,
    severity: 'HIGH',
    categoryCode: 'BRUTE_FORCE',
    definition: { schemaVersion: 1, conditions: [
      { field: 'type', operator: 'equals', value: 'authentication' },
      { field: 'action', operator: 'equals', value: 'login' },
      { field: 'status', operator: 'equals', value: 'failed' },
    ], threshold: 5, windowSeconds: 300, groupBy: ['sourceIp', 'user'] },
    mitreTechniqueIds: ['T1110'],
  },
  {
    name: 'SX-CORE-002 Credential attack indicators',
    description: 'Detects repeated failed authentication events explicitly labeled as password spraying or credential stuffing from one source IP.',
    enabled: false,
    severity: 'HIGH',
    categoryCode: 'CREDENTIAL_ATTACK',
    definition: { schemaVersion: 1, conditions: [
      { field: 'type', operator: 'equals', value: 'authentication' },
      { field: 'action', operator: 'in', value: ['password_spray', 'credential_stuffing'] },
      { field: 'status', operator: 'equals', value: 'failed' },
    ], threshold: 3, windowSeconds: 300, groupBy: ['sourceIp'] },
    mitreTechniqueIds: ['T1110'],
  },
  {
    name: 'SX-CORE-003 Privilege escalation action',
    description: 'Detects an authorization event explicitly reporting a successful privilege escalation, role elevation, or administrator grant.',
    enabled: false,
    severity: 'CRITICAL',
    categoryCode: 'PRIVILEGE_ESCALATION',
    definition: { schemaVersion: 1, conditions: [
      { field: 'type', operator: 'equals', value: 'authorization' },
      { field: 'action', operator: 'in', value: ['privilege_escalation', 'role_elevation', 'admin_grant'] },
      { field: 'status', operator: 'in', value: ['success', 'allowed'] },
    ], threshold: 1, windowSeconds: 60, groupBy: ['user', 'host'] },
    mitreTechniqueIds: [],
  },
  {
    name: 'SX-CORE-004 Suspicious account activity flag',
    description: 'Detects account events explicitly marked suspicious by the normalized source evidence.',
    enabled: false,
    severity: 'HIGH',
    categoryCode: 'SUSPICIOUS_ACCOUNT_ACTIVITY',
    definition: { schemaVersion: 1, conditions: [
      { field: 'type', operator: 'equals', value: 'account' },
      { field: 'status', operator: 'equals', value: 'suspicious' },
    ], threshold: 1, windowSeconds: 300, groupBy: ['user'] },
    mitreTechniqueIds: [],
  },
  {
    name: 'SX-CORE-005 Repeated unauthorized access attempts',
    description: 'Detects three denied access events from the same source IP against the same user within five minutes.',
    enabled: false,
    severity: 'HIGH',
    categoryCode: 'UNAUTHORIZED_ACCESS',
    definition: { schemaVersion: 1, conditions: [
      { field: 'type', operator: 'equals', value: 'access' },
      { field: 'status', operator: 'equals', value: 'denied' },
    ], threshold: 3, windowSeconds: 300, groupBy: ['sourceIp', 'user'] },
    mitreTechniqueIds: [],
  },
  {
    name: 'SX-CORE-006 Reconnaissance activity',
    description: 'Detects repeated events explicitly classified as reconnaissance scans, probes, or discovery activity from one source toward one destination.',
    enabled: false,
    severity: 'MEDIUM',
    categoryCode: 'RECONNAISSANCE',
    definition: { schemaVersion: 1, conditions: [
      { field: 'type', operator: 'equals', value: 'reconnaissance' },
      { field: 'action', operator: 'in', value: ['scan', 'probe', 'discovery'] },
    ], threshold: 3, windowSeconds: 120, groupBy: ['sourceIp', 'destinationIp'] },
    mitreTechniqueIds: [],
  },
  {
    name: 'SX-CORE-007 Suspicious network activity flag',
    description: 'Detects network events explicitly marked suspicious by normalized source evidence.',
    enabled: false,
    severity: 'HIGH',
    categoryCode: 'SUSPICIOUS_NETWORK_ACTIVITY',
    definition: { schemaVersion: 1, conditions: [
      { field: 'type', operator: 'equals', value: 'network' },
      { field: 'status', operator: 'equals', value: 'suspicious' },
    ], threshold: 1, windowSeconds: 60, groupBy: ['sourceIp', 'destinationIp'] },
    mitreTechniqueIds: [],
  },
  {
    name: 'SX-CORE-008 Phishing or social engineering report',
    description: 'Detects events explicitly classified as phishing and marked detected or reported by source evidence.',
    enabled: false,
    severity: 'HIGH',
    categoryCode: 'PHISHING_SOCIAL_ENGINEERING',
    definition: { schemaVersion: 1, conditions: [
      { field: 'type', operator: 'equals', value: 'phishing' },
      { field: 'status', operator: 'in', value: ['detected', 'reported'] },
    ], threshold: 1, windowSeconds: 300, groupBy: ['user'] },
    mitreTechniqueIds: [],
  },
  {
    name: 'SX-CORE-009 Malware event',
    description: 'Detects events explicitly classified as malware and marked detected, blocked, or executed by source evidence.',
    enabled: false,
    severity: 'HIGH',
    categoryCode: 'MALWARE',
    definition: { schemaVersion: 1, conditions: [
      { field: 'type', operator: 'equals', value: 'malware' },
      { field: 'status', operator: 'in', value: ['detected', 'blocked', 'executed'] },
    ], threshold: 1, windowSeconds: 60, groupBy: ['host'] },
    mitreTechniqueIds: [],
  },
  {
    name: 'SX-CORE-010 Ransomware event',
    description: 'Detects events explicitly classified as ransomware and marked detected, blocked, or executed by source evidence.',
    enabled: false,
    severity: 'CRITICAL',
    categoryCode: 'RANSOMWARE',
    definition: { schemaVersion: 1, conditions: [
      { field: 'type', operator: 'equals', value: 'ransomware' },
      { field: 'status', operator: 'in', value: ['detected', 'blocked', 'executed'] },
    ], threshold: 1, windowSeconds: 60, groupBy: ['host'] },
    mitreTechniqueIds: [],
  },
  {
    name: 'SX-CORE-011 Denial of service indicators',
    description: 'Detects repeated network events explicitly labeled DoS or DDoS against the same destination or host within one minute.',
    enabled: false,
    severity: 'CRITICAL',
    categoryCode: 'DENIAL_OF_SERVICE',
    definition: { schemaVersion: 1, conditions: [
      { field: 'type', operator: 'equals', value: 'network' },
      { field: 'action', operator: 'in', value: ['dos', 'ddos'] },
      { field: 'status', operator: 'in', value: ['detected', 'active', 'blocked'] },
    ], threshold: 3, windowSeconds: 60, groupBy: ['destinationIp', 'host'] },
    mitreTechniqueIds: [],
  },
  {
    name: 'SX-CORE-012 Data exfiltration event',
    description: 'Detects data-transfer events explicitly labeled as exfiltration and marked detected, blocked, or successful by source evidence.',
    enabled: false,
    severity: 'CRITICAL',
    categoryCode: 'DATA_EXFILTRATION',
    definition: { schemaVersion: 1, conditions: [
      { field: 'type', operator: 'equals', value: 'data_transfer' },
      { field: 'action', operator: 'equals', value: 'exfiltration' },
      { field: 'status', operator: 'in', value: ['detected', 'blocked', 'success'] },
    ], threshold: 1, windowSeconds: 300, groupBy: ['user', 'host'] },
    mitreTechniqueIds: [],
  },
  {
    name: 'SX-CORE-013 Web application attack event',
    description: 'Detects web-application events explicitly labeled as SQL injection, XSS, path traversal, or command injection.',
    enabled: false,
    severity: 'HIGH',
    categoryCode: 'WEB_APPLICATION_ATTACK',
    definition: { schemaVersion: 1, conditions: [
      { field: 'type', operator: 'equals', value: 'web_application' },
      { field: 'action', operator: 'in', value: ['sql_injection', 'xss', 'path_traversal', 'command_injection'] },
      { field: 'status', operator: 'in', value: ['detected', 'blocked', 'attempted'] },
    ], threshold: 1, windowSeconds: 60, groupBy: ['sourceIp', 'destinationIp'] },
    mitreTechniqueIds: [],
  },
  {
    name: 'SX-CORE-014 Insider threat classification',
    description: 'Detects events explicitly classified by source evidence as suspected or detected insider-threat activity; it does not infer insider intent.',
    enabled: false,
    severity: 'HIGH',
    categoryCode: 'INSIDER_THREAT',
    definition: { schemaVersion: 1, conditions: [
      { field: 'type', operator: 'equals', value: 'insider_threat' },
      { field: 'status', operator: 'in', value: ['suspected', 'detected'] },
    ], threshold: 1, windowSeconds: 300, groupBy: ['user', 'host'] },
    mitreTechniqueIds: [],
  },
  {
    name: 'SX-CORE-015 Supply chain compromise classification',
    description: 'Detects events explicitly classified by source evidence as detected or confirmed supply-chain compromise activity.',
    enabled: false,
    severity: 'CRITICAL',
    categoryCode: 'SUPPLY_CHAIN_COMPROMISE',
    definition: { schemaVersion: 1, conditions: [
      { field: 'type', operator: 'equals', value: 'supply_chain_compromise' },
      { field: 'status', operator: 'in', value: ['detected', 'confirmed'] },
    ], threshold: 1, windowSeconds: 300, groupBy: ['host'] },
    mitreTechniqueIds: [],
  },
]);

module.exports = { INITIAL_RULES };
