'use strict';
const ui=window.SentinelXUi;
const el=id=>document.getElementById(id);let generation=0,page=1,responsePage=1,activeFilters=new URLSearchParams(),canManage=false,canInvestigate=false,canRespond=false,currentUserId=null,currentIncidentId=null,selectableCategories=[];
function message(text,error=false,success=false){el('message').textContent=error?`Error: ${text}`:text;el('message').classList.toggle('error',error);el('message').classList.toggle('success',success&&!error);if(error||success)el('message').scrollIntoView({block:'center'});}
function clearDetail(){currentIncidentId=null;el('detail-panel').hidden=true;el('detail-fields').replaceChildren();el('alert-rows').replaceChildren();el('affected-entities').replaceChildren();el('investigation-event-rows').replaceChildren();el('investigation-timeline').replaceChildren();el('investigation-notes').replaceChildren();el('investigation-workspace').hidden=true;el('investigation-note-form').hidden=true;el('response-action-rows').replaceChildren();el('response-workflow').hidden=true;el('response-form').hidden=true;el('response-form').reset();el('response-confirmation').disabled=true;el('response-page').textContent='';el('response-previous').disabled=true;el('response-next').disabled=true;el('investigation-note-content').value='';el('investigation-note-alerts').value='';el('investigation-note-events').value='';el('assessment-form').hidden=true;el('assignment-form').hidden=true;el('status-form').hidden=true;el('assessment-reason').value='';el('assignment-reason').value='';el('status-reason').value='';el('resolution-note').value='';}
function clearData(){el('rows').replaceChildren();el('results').textContent='';el('page').textContent='';el('previous').disabled=true;el('next').disabled=true;clearDetail();}
function reset(){ui.clearAccess();generation++;clearData();el('login-panel').hidden=false;el('identity-panel').hidden=true;el('incidents-panel').hidden=true;el('create-panel').hidden=true;canManage=false;canInvestigate=false;canRespond=false;responsePage=1;currentUserId=null;selectableCategories=[];}
async function request(path,options={}){const response=await fetch(path,{credentials:'same-origin',cache:'no-store',...options});const body=response.status===204?null:await response.json();if(!response.ok){const error=new Error(body?.error||'Request failed.');error.status=response.status;throw error;}return body;}
function handleError(error){if(error.status===401||error.status===403)reset();if(error.status===401)return message('Sign in to continue.');message(ui.safeError(error),true);}
function addField(label,value){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value??'Unknown';el('detail-fields').append(dt,dd);}
function definition(container,label,value){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;container.append(dt,dd);}
function mlEvidenceText(evidence){if(!evidence)return'historical';if(evidence.status==='ready'&&Number.isFinite(evidence.anomalyScore))return`ready · score ${evidence.anomalyScore.toFixed(6)} · supporting only`;return`${evidence.status||'unavailable'} · supporting only`;}
function renderInvestigation(workspace){const entities=el('affected-entities');for(const [field,label] of [['user','Users'],['host','Hosts'],['sourceIp','Source IPs'],['destinationIp','Destination IPs']])definition(entities,label,workspace.affectedEntities[field].length?workspace.affectedEntities[field].join(', '):'None');for(const event of workspace.events){const tr=document.createElement('tr');for(const value of [event.timestamp,`${event.source} / ${event.type}`,event.severity??'Unknown',event.user??'None',event.host??'None',event.sourceIp??'None',event.destinationIp??'None',event.action??'None',event.status??'None']){const td=document.createElement('td');td.textContent=value;tr.append(td);}el('investigation-event-rows').append(tr);}for(const item of workspace.timeline){const li=document.createElement('li'),strong=document.createElement('strong'),span=document.createElement('span');strong.textContent=`${item.timestamp} · ${item.type}: `;span.textContent=item.summary;li.append(strong,span);el('investigation-timeline').append(li);}if(!workspace.notes.length){const p=document.createElement('p');p.textContent='No analyst findings recorded yet.';el('investigation-notes').append(p);}for(const note of workspace.notes){const article=document.createElement('article'),heading=document.createElement('p'),body=document.createElement('p'),refs=document.createElement('p');article.className='finding';heading.textContent=`${note.createdAt} · ${note.author.displayName??'Analyst'}`;body.textContent=note.content;const alertRefs=note.evidence.alertIds??[],eventRefs=note.evidence.eventIds??[];refs.textContent=`Evidence: ${alertRefs.length} alert(s), ${eventRefs.length} event(s)`;article.append(heading,body,refs);el('investigation-notes').append(article);}el('investigation-note-form').hidden=!canInvestigate;el('investigation-workspace').hidden=false;}
function referenceIds(value){return [...new Set(value.split(/[\s,]+/).map(item=>item.trim()).filter(Boolean))];}
function renderResponse(data,status){
  const rows=el('response-action-rows');
  if(!data.actions.length){const p=document.createElement('p');p.textContent='No manual response actions have been recorded on this page.';rows.append(p);}
  for(const action of data.actions){
    const article=document.createElement('article'),heading=document.createElement('p'),actor=document.createElement('p'),reason=document.createElement('p'),outcome=document.createElement('p');
    article.className='finding';
    heading.textContent=action.performedAt+' · '+action.action+' · '+(action.succeeded?'Reported successful':'Reported unsuccessful');
    actor.textContent='Recorded by: '+(action.authorizedBy.displayName||action.authorizedBy.id);
    reason.textContent='Reason: '+action.reason;
    outcome.textContent='Reported outcome: '+(action.result?.summary||'None');
    article.append(heading,actor,reason,outcome);rows.append(article);
  }
  el('response-page').textContent='Response page '+data.page;
  el('response-previous').disabled=data.page<=1;
  el('response-next').disabled=!data.hasMore;
  el('response-form').hidden=!canRespond||['RESOLVED','DISMISSED'].includes(status);
  el('response-workflow').hidden=false;
}
function syncResponseConfirmation(){
  const available=el('response-action').value==='CONTAINMENT'&&el('response-succeeded').checked;
  el('response-confirmation').disabled=!available;
  if(!available)el('response-confirmation').checked=false;
}
function populateAssessment(incident){const select=el('assessment-category');select.replaceChildren();const none=document.createElement('option');none.value='';none.textContent='Unclassified';select.append(none);for(const category of selectableCategories){const option=document.createElement('option');option.value=category.code;option.textContent=`${category.name} (${category.code})`;select.append(option);}if(incident.categoryCode&&!selectableCategories.some(category=>category.code===incident.categoryCode)){const current=document.createElement('option');current.value=incident.categoryCode;current.textContent=`${incident.categoryCode} (current, unavailable)`;select.append(current);}select.value=incident.categoryCode||'';el('assessment-severity').value=incident.severity;}

async function inspect(id){if(id!==currentIncidentId)responsePage=1;const current=++generation;clearDetail();try{const {incident}=await request(`/api/incidents/${encodeURIComponent(id)}`);if(current!==generation)return;if(canManage){const catalog=await request('/api/threat-categories?selectable=true');if(current!==generation)return;selectableCategories=catalog.categories;}const {investigation}=await request(`/api/investigations/${encodeURIComponent(id)}`);if(current!==generation)return;const responseHistory=await request('/api/responses/'+encodeURIComponent(id)+'?page='+responsePage);if(current!==generation)return;currentIncidentId=incident.id;for(const [label,value] of Object.entries({ID:incident.id,Title:incident.title,Description:incident.description||'None',Created:incident.createdAt,Updated:incident.updatedAt,Severity:incident.severity,RiskScore:incident.risk?`${incident.risk.score} / 100`:'Unavailable',RiskEvidenceEvents:incident.risk?String(incident.risk.eventCount):'Unavailable',RiskFormula:incident.risk?`v${incident.risk.formulaVersion}`:'Unavailable',RiskCalculated:incident.risk?.calculatedAt||'Unavailable',Category:incident.categoryCode||'Unclassified',Status:incident.status,Assignee:incident.assignedTo?`${incident.assignedTo.displayName||'User'} (${incident.assignedTo.id})`:'Unassigned',AssessmentUpdated:incident.assessmentUpdatedAt||'Never',AssessmentBy:incident.assessmentUpdatedBy||'None',Resolution:incident.resolutionNote||'None'}))addField(label,value);for(const alert of incident.alerts){const tr=document.createElement('tr');for(const value of [alert.id,alert.timestamp,alert.severity,alert.threat,alert.source,alert.status,mlEvidenceText(alert.mlEvidence)]){const td=document.createElement('td');td.textContent=value??'Unknown';tr.append(td);}el('alert-rows').append(tr);}renderInvestigation(investigation);renderResponse(responseHistory,incident.status);const terminal=['RESOLVED','DISMISSED'].includes(incident.status);if(canManage)populateAssessment(incident);el('assessment-form').hidden=!canManage;el('assignment-form').hidden=!canManage||terminal;el('status-form').hidden=!canManage||terminal;el('detail-panel').hidden=false;el('detail-panel').focus();message('Incident loaded.');}catch(error){if(current===generation)handleError(error);}}
async function load(){const current=++generation;clearData();ui.loading('Loading incidents…');try{const access=await request('/api/access/me');if(current!==generation)return;ui.applyAccess(access);currentUserId=access.user.id;el('login-panel').hidden=true;el('identity-panel').hidden=false;el('identity').textContent=`${access.user.displayName} · ${access.roles.join(', ')||'No role assigned'}`;if(!access.permissions.includes('incidents.read')){el('incidents-panel').hidden=true;message('Your account does not have permission to view incidents.',true);return;}canManage=access.permissions.includes('incidents.manage');canInvestigate=access.permissions.includes('investigations.write');canRespond=access.permissions.includes('responses.execute');el('create-panel').hidden=!canManage;const params=new URLSearchParams(activeFilters);params.set('page',String(page));const data=await request(`/api/incidents?${params}`);if(current!==generation)return;for(const incident of data.incidents){const tr=document.createElement('tr');for(const value of [incident.createdAt,incident.title,incident.severity,incident.risk?`${incident.risk.score}/100`:'Unavailable',incident.categoryCode||'Unclassified',incident.status,incident.assignedTo?.displayName||'Unassigned']){const td=document.createElement('td');td.textContent=value;tr.append(td);}const td=document.createElement('td'),button=document.createElement('button');button.type='button';button.textContent='Inspect';button.setAttribute('aria-label',`Inspect incident ${incident.id}`);button.addEventListener('click',()=>inspect(incident.id));td.append(button);tr.append(td);el('rows').append(tr);}el('incidents-panel').hidden=false;el('results').textContent=data.incidents.length?`${data.incidents.length} ${data.incidents.length===1?'incident':'incidents'} on this page.`:'No incidents match these filters.';el('page').textContent=`Page ${data.page}`;el('previous').disabled=page<=1;el('next').disabled=!data.hasMore;message('Incidents loaded.');}catch(error){if(current===generation)handleError(error);}}
el('filters').addEventListener('submit',event=>{event.preventDefault();const params=new URLSearchParams();try{for(const [key,value] of new FormData(event.currentTarget))if(value.trim())params.set(key,['from','to'].includes(key)?new Date(value).toISOString():value.trim());activeFilters=params;page=1;load();}catch{clearData();message('Enter valid incident filters.',true);}});
el('clear').addEventListener('click',()=>{el('filters').reset();activeFilters=new URLSearchParams();page=1;load();});el('previous').addEventListener('click',()=>{if(page>1){page--;load();}});el('next').addEventListener('click',()=>{if(page<2000){page++;load();}});
el('create-form').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,button=form.querySelector('button');button.disabled=true;try{const alertIds=[...new Set(el('create-alerts').value.split(/[\s,]+/).map(v=>v.trim()).filter(Boolean))];await request('/api/incidents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:el('create-title').value,description:el('create-description').value,alertIds,assignedTo:el('assign-self').checked?currentUserId:null,reason:el('create-reason').value})});form.reset();page=1;await load();message('Incident created.',false,true);}catch(error){handleError(error);}finally{button.disabled=false;}});
el('investigation-note-form').addEventListener('submit',async event=>{event.preventDefault();if(!currentIncidentId)return;const id=currentIncidentId,button=event.currentTarget.querySelector('button');button.disabled=true;try{await request(`/api/investigations/${encodeURIComponent(id)}/notes`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:el('investigation-note-content').value,alertIds:referenceIds(el('investigation-note-alerts').value),eventIds:referenceIds(el('investigation-note-events').value)})});await inspect(id);message('Finding recorded.');}catch(error){handleError(error);}finally{button.disabled=false;}});
el('response-action').addEventListener('change',syncResponseConfirmation);
el('response-succeeded').addEventListener('change',syncResponseConfirmation);
el('response-previous').addEventListener('click',()=>{const id=currentIncidentId;if(id&&responsePage>1){responsePage--;inspect(id);}});
el('response-next').addEventListener('click',()=>{const id=currentIncidentId;if(id&&responsePage<2000){responsePage++;inspect(id);}});
el('response-form').addEventListener('submit',async event=>{
  event.preventDefault();if(!currentIncidentId)return;
  const id=currentIncidentId,button=event.currentTarget.querySelector('button');
  const payload={action:el('response-action').value,reason:el('response-reason').value,details:el('response-details').value,
    succeeded:el('response-succeeded').checked,containmentPerformed:el('response-confirmation').checked};
  if(payload.action==='CONTAINMENT'&&payload.succeeded&&!payload.containmentPerformed){message('Confirm that manual containment was actually performed before recording success.',true);return;}
  button.disabled=true;
  try{await request('/api/responses/'+encodeURIComponent(id)+'/actions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});responsePage=1;await load();await inspect(id);message('Manual response recorded.');}
  catch(error){handleError(error);}finally{button.disabled=false;}
});
el('assessment-form').addEventListener('submit',async event=>{event.preventDefault();if(!currentIncidentId)return;const id=currentIncidentId,button=event.currentTarget.querySelector('button');button.disabled=true;try{await request(`/api/incidents/${encodeURIComponent(id)}/assessment`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({categoryCode:el('assessment-category').value||null,severity:el('assessment-severity').value,reason:el('assessment-reason').value})});await load();await inspect(id);}catch(error){handleError(error);}finally{button.disabled=false;}});
el('assignment-form').addEventListener('submit',async event=>{event.preventDefault();if(!currentIncidentId)return;const id=currentIncidentId,button=event.currentTarget.querySelector('button');button.disabled=true;try{await request(`/api/incidents/${encodeURIComponent(id)}/assignment`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({assignedTo:el('assignment-choice').value==='self'?currentUserId:null,reason:el('assignment-reason').value})});await load();await inspect(id);}catch(error){handleError(error);}finally{button.disabled=false;}});
el('status-form').addEventListener('submit',async event=>{event.preventDefault();if(!currentIncidentId)return;const id=currentIncidentId,status=el('incident-status').value,terminal=['RESOLVED','DISMISSED'].includes(status),button=event.currentTarget.querySelector('button');button.disabled=true;try{await request(`/api/incidents/${encodeURIComponent(id)}/status`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status,reason:el('status-reason').value,resolutionNote:terminal?el('resolution-note').value:null})});await load();await inspect(id);}catch(error){handleError(error);}finally{button.disabled=false;}});
el('login-form').addEventListener('submit',async event=>{event.preventDefault();const button=event.currentTarget.querySelector('button');button.disabled=true;try{const login=await request('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:el('email').value,password:el('password').value})});if(ui.beginTwoFactor(login))return;await load();}catch(error){handleError(error);}finally{el('password').value='';button.disabled=false;}});el('logout').addEventListener('click',async()=>{reset();try{await request('/api/auth/logout',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});message('Signed out.');}catch(error){handleError(error);}});load();
