const test = require('node:test');
const assert = require('node:assert/strict');
const { randomUUID, randomBytes } = require('node:crypto');
const { createPool } = require('../../src/data/pool');
const { authRepository } = require('../../src/data/auth-repository');
const { hashPassword } = require('../../src/auth/passwords');
const { authService, hashToken } = require('../../src/auth/service');
const { configFromEnv } = require('../../src/auth/config');
const { createServer } = require('../../src/api/server');
const { migrationSql } = require('../../scripts/migrate');
const { executeSql } = require('../../src/data/postgres');
test('real PostgreSQL authentication, session expiry/revocation and transactional audit', async t => {
  assert.equal(process.env.SENTINELX_TEST_DATABASE, '1', 'Select a disposable database and set SENTINELX_TEST_DATABASE=1.');
  executeSql(migrationSql());
  executeSql(migrationSql());
  const pool = createPool();
  const repository = authRepository(pool);
  const config = configFromEnv({});
  const service = authService(repository, config);
  const password = 'Synthetic integration passphrase only 🔐';
  const email = `synthetic-${randomUUID()}@example.invalid`;
  const userId = await repository.createUser(email, 'Synthetic tester', await hashPassword(password), 'synthetic provisioning operator');
  await assert.rejects(repository.createUser(email.toUpperCase(), 'Duplicate tester', 'unused hash', 'synthetic provisioning operator'), { code: '23505' });
  const server = createServer(service, config);
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  t.after(async () => {
    await new Promise(resolve => { server.close(resolve); server.closeAllConnections(); });
    await pool.query('DELETE FROM audit_logs WHERE actor_id = $1 OR target_id = $1', [userId]);
    await pool.query('DELETE FROM auth_sessions WHERE user_id = $1', [userId]);
    await pool.query('DELETE FROM users WHERE id = $1', [userId]);
    await pool.end();
  });
  const base = `http://127.0.0.1:${server.address().port}`;
  const post = (path, body, cookie) => fetch(`${base}${path}`, { method: 'POST', headers: { Origin: config.origin, 'Content-Type': 'application/json', ...(cookie ? { Cookie: cookie } : {}) }, body: JSON.stringify(body) });
  let response = await post('/api/auth/login', { email: email.toUpperCase(), password });
  assert.equal(response.status, 200);
  const safe = await response.json();
  assert.deepEqual(safe, { user: { id: userId, email, displayName: 'Synthetic tester' } });
  const cookie = response.headers.get('set-cookie').split(';')[0];
  const token = cookie.split('=')[1];
  const persisted = await pool.query('SELECT token_hash FROM auth_sessions WHERE user_id = $1', [userId]);
  assert.equal(persisted.rows[0].token_hash, hashToken(token));
  assert.notEqual(persisted.rows[0].token_hash, token);
  assert.equal((await fetch(`${base}/api/auth/me`, { headers: { Cookie: cookie } })).status, 200);
  response = await post('/api/auth/logout', {}, cookie);
  assert.equal(response.status, 204);
  assert.match(response.headers.get('set-cookie'), /Max-Age=0/);
  assert.equal((await fetch(`${base}/api/auth/me`, { headers: { Cookie: cookie } })).status, 401);
  assert.equal((await post('/api/auth/logout', {}, cookie)).status, 401);
  for (const credentials of [{ email, password: 'wrong' }, { email: 'missing@example.invalid', password }, { email: "'/**/OR/**/1=1--@example.invalid", password }]) {
    response = await post('/api/auth/login', credentials);
    assert.equal(response.status, 401);
    assert.deepEqual(await response.json(), { error: 'Invalid email or password.' });
  }
  await pool.query('UPDATE users SET active = false WHERE id = $1', [userId]);
  response = await post('/api/auth/login', { email, password });
  assert.equal(response.status, 401);
  assert.deepEqual(await response.json(), { error: 'Invalid email or password.' });
  await pool.query('UPDATE users SET active = true WHERE id = $1', [userId]);
  const active = await service.login({ email, password });
  await pool.query('UPDATE users SET active = false WHERE id = $1', [userId]);
  await assert.rejects(service.currentUser(active.token), { status: 401 });
  await pool.query('UPDATE users SET active = true WHERE id = $1', [userId]);
  await assert.rejects(service.currentUser(active.token), { status: 401 });
  const reset = await service.login({ email, password });
  const staleUser = await repository.findUser(email);
  await pool.query('UPDATE users SET password_hash = $1 WHERE id = $2', [await hashPassword(password), userId]);
  await assert.rejects(service.currentUser(reset.token), { status: 401 });
  assert.equal(await repository.createSession(staleUser, hashToken(randomBytes(32).toString('base64url')), config.sessionSeconds), null);
  const idle = await service.login({ email, password });
  await pool.query("UPDATE auth_sessions SET created_at = now() - interval '2 hours', last_seen_at = now() - interval '31 minutes' WHERE token_hash = $1", [hashToken(idle.token)]);
  await assert.rejects(service.currentUser(idle.token), { status: 401 });
  const expired = await service.login({ email, password });
  await pool.query("UPDATE auth_sessions SET created_at = now() - interval '10 hours', last_seen_at = now() - interval '9 hours', expires_at = now() - interval '1 hour' WHERE token_hash = $1", [hashToken(expired.token)]);
  await assert.rejects(service.currentUser(expired.token), { status: 401 });
  await assert.rejects(service.currentUser(randomBytes(32).toString('base64url')), { status: 401 });
  const actions = await pool.query('SELECT action FROM audit_logs WHERE actor_id = $1 OR target_id = $1', [userId]);
  for (const action of ['AUTH_USER_PROVISIONED', 'AUTH_LOGIN_SUCCEEDED', 'AUTH_LOGOUT']) assert.ok(actions.rows.some(row => row.action === action));
  const failures = await pool.query("SELECT count(*)::int AS count FROM audit_logs WHERE action = 'AUTH_LOGIN_FAILED' AND actor_id IS NULL");
  assert.ok(failures.rows[0].count >= 4);
  // A missing audit table must prevent session creation and roll back its insert.
  const client = await pool.connect();
  const auditLogout = await service.login({ email, password });
  try {
    await client.query('BEGIN');
    await client.query('ALTER TABLE audit_logs RENAME TO audit_logs_temporarily_unavailable');
    // Nested BEGIN is avoided by substituting only the repository transaction commands.
    const savepointRepo = authRepository({ connect: async () => ({ query: (sql, params) => client.query(sql === 'BEGIN' ? 'SAVEPOINT auth_check' : sql === 'COMMIT' ? 'RELEASE SAVEPOINT auth_check' : sql === 'ROLLBACK' ? 'ROLLBACK TO SAVEPOINT auth_check' : sql, params), release() {} }) });
    const digest = hashToken(randomBytes(32).toString('base64url'));
    const user = await repository.findUser(email);
    await assert.rejects(savepointRepo.createSession(user, digest, config.sessionSeconds));
    const remaining = await client.query('SELECT id FROM auth_sessions WHERE token_hash = $1', [digest]);
    assert.equal(remaining.rowCount, 0);
    await assert.rejects(savepointRepo.logout(hashToken(auditLogout.token), config.idleSeconds));
    const notRevoked = await client.query('SELECT revoked_at FROM auth_sessions WHERE token_hash = $1', [hashToken(auditLogout.token)]);
    assert.equal(notRevoked.rows[0].revoked_at, null);
    await client.query('ROLLBACK');
  } finally { client.release(); }
});
