const test = require('node:test');
const assert = require('node:assert/strict');
const { ingestionService, approvedSources } = require('../../src/events/ingestion');
const { AuthError } = require('../../src/auth/errors');
const { configFromEnv } = require('../../src/auth/config');
const { createServer } = require('../../src/api/server');
const fixture = require('../../fixtures/events/simulated-login.json');
test('ingestion validates approved configuration and role/source boundaries', async () => {
  assert.deepEqual(approvedSources({}), ['sentinelx-simulated']);
  for (const value of ['', 'one,one', 'one,,two', 'bad source']) assert.throws(() => approvedSources({ EVENT_INGEST_SOURCES: value }));
  let calls = 0;
  const service = ingestionService({ create: async (event, actor) => { calls++; assert.equal(actor, 'actor'); return { id: 'id', receivedAt: 'time', normalizedAt: 'time' }; } }, { me: async token => ({ user: { id: 'actor' }, roles: [token] }) }, approvedSources({}));
  for (const role of ['Administrator', 'Security Analyst']) assert.equal((await service.ingest(role, fixture)).id, 'id');
  for (const role of ['Viewer/Management', 'Owner', '']) await assert.rejects(service.ingest(role, fixture), { status: 403 });
  await assert.rejects(service.ingest('Administrator', { ...fixture, source: 'unapproved' }), { status: 403 });
  await assert.rejects(service.ingest('Administrator', { ...fixture, sourceIp: 'invalid' }));
  assert.equal(calls, 2);
});
test('event HTTP boundary rejects invalid payloads, identity, origins and methods', async t => {
  const config = configFromEnv({}); let calls = 0;
  const access = { me: async token => { if (!token) throw new AuthError(401, 'Authentication required.'); return { user: { id: 'actor' }, roles: [token] }; } };
  const service = ingestionService({ create: async event => { calls++; if (event.type === 'backend-failure') throw new Error('private SQL detail'); return { id: 'synthetic-id', receivedAt: 'time', normalizedAt: 'time' }; } }, access, approvedSources({}));
  const server = createServer({}, config, null, service);
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  t.after(() => new Promise(resolve => { server.close(resolve); server.closeAllConnections(); }));
  const url = `http://127.0.0.1:${server.address().port}/api/events`;
  const headers = { Origin: config.origin, 'Content-Type': 'application/json', Cookie: `${config.cookieName}=Administrator` };
  const post = (body, patch = {}, path = url) => fetch(path, { method: 'POST', headers: { ...headers, ...patch }, body: typeof body === 'string' ? body : JSON.stringify(body) });
  assert.equal((await post(fixture)).status, 201);
  assert.equal((await post(fixture, { Cookie: '' })).status, 401);
  assert.equal((await post(fixture, { Cookie: `${config.cookieName}=Viewer/Management`, 'X-Role': 'Administrator' })).status, 403);
  assert.equal((await post(fixture, { Origin: 'http://untrusted.invalid' })).status, 403);
  assert.equal((await post(fixture, { Origin: '' })).status, 403);
  assert.equal((await post(fixture, { 'Content-Type': 'text/plain' })).status, 415);
  for (const body of ['{', [], { ...fixture, severity: 'INVALID' }, { ...fixture, extra: true }]) assert.equal((await post(body)).status, 400);
  assert.equal((await post({ ...fixture, rawData: { large: 'x'.repeat(9000) } })).status, 413);
  assert.equal((await post(fixture, {}, `${url}?source=x`)).status, 404);
  assert.equal((await fetch(url)).status, 405);
  const failed = await post({ ...fixture, type: 'backend-failure' });
  assert.equal(failed.status, 503); assert.deepEqual(await failed.json(), { error: 'Event ingestion temporarily unavailable.' });
  assert.equal(calls, 2);
});
